### ISSUE TITLE
Guides only work on first Artboard

### ISSUE THREAD

**Issue by jsengstrom** [guideguide/support#191]
I am using the trial version of GuideGuide before deciding whether to purchase. It looks great but the guides are pasting on top of the first artboard, no matter which I have selected in my layers tab.

Not sure if this is a limitation of the trail version and this will work once I have purchased the plugin?

Thanks for your help.

**Comment by cameronmcefee** [comment]
Hi @jsengatrom! Please update to the most recent version (4.1.1). Adobe published an update yesterday and I published one this morning. It should resolve the issue.

http://guideguide.me

**Comment by TwanBB** [comment]
I have the same problem, updating tot 4.1.1 doesn't seem to solve the problem.
